version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&  python manage.py migrate && python manage.py create_root_user && gunicorn wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 120"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8080:8000"
      
    
    

  

  


volumes:
  postgres_data:
  static_volume:
  media_volume:
