apiVersion: latest 
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080

---
apiVersion: apps/latest 
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
        - name: migrate
          image: rsu-web-app:latest 
          imagePullPolicy: IfNotPresent
          # أضفنا سليب بسيط للتأكد من جاهزية القاعدة
          command: ["sh", "-c", "sleep 5 && python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py create_root_user"]
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_DEBUG
              value: "True"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              value: "db"
            # الحل هنا: إجبار البورت يكون رقم
            - name: DB_PORT
              value: "5432"

      containers:
        - name: django
          image: rsu-web-app:latest 
          imagePullPolicy: IfNotPresent
          command: ["gunicorn", "wsgi:application", "--bind", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_DEBUG
              value: "True"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rsu-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              value: "db"
            # نكرر الحل هنا برضه
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: static-storage
              mountPath: /app/static
            - name: media-storage
              mountPath: /app/media
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-pvc
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
