apiVersion: v1
kind: Secret
metadata:
  name: rsu-secrets
type: Opaque
# استخدمنا stringData عشان نكتب البيانات زي ما هي، وكوبرنيتيس حيشفرها براه داخلياً
stringData:
  DJANGO_SECRET_KEY: "change_this_secret_key_in_prod"
  DB_NAME: "rsu_db"
  DB_USER: "rsu_user"
  DB_PASSWORD: "rsupassword"
