apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # يعني حاوية واحدة بس تقدر تقرأ وتكتب عليه في نفس الوقت
  resources:
    requests:
      storage: 2Gi # طلبنا مساحة 1 جيجا، ممكن تزيدها لو حابب

---
# 2. هاردسك ملفات الاستاتيك (CSS, JS)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# 3. هاردسك الميديا (الصور والملفات المرفوعة)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
